### PR TITLE
Removing Parallels Virtualization SDK dependency from PDfM 19.0.0

### LINKED ISSUE #36: Packer fails "Parallels Virtualization SDK is not installed" when it is installed
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Packer fails to detect the installed Parallels Virtualization SDK.

```
joe.gorse@Joes-MacBook-Pro bento % ls /Library/Frameworks/ParallelsVirtualizationSDK.framework
Headers				Libraries			ParallelsVirtualizationSDK	Resources			Versions
```

```
joe.gorse@Joes-MacBook-Pro bento % packer build -only=parallels-iso packer_templates/ubuntu/ubuntu-20.04-arm64.json
parallels-iso: output will be in this color.

Build 'parallels-iso' errored after 1 millisecond 777 microseconds: Failed creating Parallels driver: Parallels Virtualization SDK is not installed

==> Wait completed after 1 millisecond 817 microseconds

==> Some builds didn't complete successfully and had errors:
--> parallels-iso: Failed creating Parallels driver: Parallels Virtualization SDK is not installed

==> Builds finished but no artifacts were created.
```

#### Reproduction Steps

```
brew install vagrant
vagrant plugin install vagrant-parallels

git clone https://github.com/chef/bento && cd bento
# sudo gem install mixlib-shellout
packer build -only=parallels-iso packer_templates/ubuntu/ubuntu-20.04-arm64.json
```

### Plugin and Packer version

packer --version
1.8.0

### Simplified Packer Buildfile

https://github.com/chef/bento/blob/main/packer_templates/ubuntu/ubuntu-20.04-arm64.json

### Operating system and Environment details

macOS Monterey
2022 Macbook Pro
m1 aarch64

### Log Fragments and crash.log files

```
2022/03/31 11:07:09 Build debug mode: true
2022/03/31 11:07:09 Force build: false
2022/03/31 11:07:09 On error: ask
2022/03/31 11:07:09 Debug enabled, so waiting for build to finish: parallels-iso
2022/03/31 11:07:09 Starting build run: parallels-iso
2022/03/31 11:07:09 Running builder: parallels-iso
2022/03/31 11:07:09 [INFO] (telemetry) Starting builder parallels-iso
2022/03/31 11:07:09 [INFO] (telemetry) ending parallels-iso
2022/03/31 11:07:09 ui error: Build 'parallels-iso' errored after 3 milliseconds 544 microseconds: Failed creating Parallels driver: Parallels Virtualization SDK is not installed
2022/03/31 11:07:09 Waiting on builds to complete...
2022/03/31 11:07:09 ui:
==> Wait completed after 3 milliseconds 985 microseconds
2022/03/31 11:07:09 machine readable: error-count []string{"1"}
2022/03/31 11:07:09 ui error:
==> Some builds didn't complete successfully and had errors:
2022/03/31 11:07:09 machine readable: parallels-iso,error []string{"Failed creating Parallels driver: Parallels Virtualization SDK is not installed"}
2022/03/31 11:07:09 ui error: --> parallels-iso: Failed creating Parallels driver: Parallels Virtualization SDK is not installed
2022/03/31 11:07:09 ui:
==> Builds finished but no artifacts were created.
2022/03/31 11:07:09 [INFO] (telemetry) Finalizing.
2022/03/31 11:07:09 waiting for all plugin processes to complete...
2022/03/31 11:07:09 /opt/homebrew/Cellar/packer/1.8.0/libexec/bin/packer: plugin process exited
2022/03/31 11:07:09 /opt/homebrew/Cellar/packer/1.8.0/libexec/bin/packer: plugin process exited
2022/03/31 11:07:09 /opt/homebrew/Cellar/packer/1.8.0/libexec/bin/packer: plugin process exited
```

### PR DESCRIPTION
**Pull request by sai-kumar-peddireddy**
With these changes from PDfM 19.0.0 no need to install parallels Python SDK

### Changes
* Sending scan codes using prlctl send-key-event command
* Initializing the `PYTHONPATH` env variable to fix #36 
* Introduced a check for python sdk only if PDfM is less than 19.0.0

Closes #36

### CODE REVIEW

File: builder/parallels/common/driver.go [hunk 1]
```diff
@@ -78,23 +82,20 @@ func NewDriver() (Driver, error) {
...
 		var err error
 		prlctlPath, err = exec.LookPath("prlctl")
 		if err != nil {
 			return nil, err
 		}
 	}
-
 	log.Printf("prlctl path: %s", prlctlPath)
 
+	err := checkforPythonSDK(prlctlPath)
```
Comment (cjlapao) [inline builder/parallels/common/driver.go:94]: when defining an error as an output and an if for that error the most common way of doing it is
if err := checkforPythonSDK(prlctlPath); err != nil {
  return nil, err
}
but you don't need to change it, just easier to read

**Review by cjlapao — APPROVED** [review]

File: builder/parallels/common/driver.go (hunk 1 above)
Comment (sai-kumar-peddireddy) [reply builder/parallels/common/driver.go:94]: I will adapt it for my next changes. I should learn Go way of writing :). I did it as a C++ programer. Thanks for mentioning @cjlapao
