### PR TITLE
Resolve ip is not detected if dhcp_leases file is missing

### LINKED ISSUE #103: IP detection fails due to 'parallels_dhcp_leases: no such file or directory'
#### Overview of the Issue

When running packer build, system is waiting for SSH for a very long time.

#### Reproduction Steps

To reproduce, just run packer build. 

### Plugin and Packer version

Latest version. 

### Simplified Packer Buildfile

packer-examples, macOS script

### Operating system and Environment details

Host : macOS ARM Sonoma, Guest, macOS 13

### Log Fragments and crash.log files

2024/02/08 13:21:31 packer-plugin-parallels_v1.1.5_x5.0_darwin_arm64 plugin: 2024/02/08 13:21:31 Found MAC address for NIC: net0 - 001C42EE35B5
2024/02/08 13:21:31 packer-plugin-parallels_v1.1.5_x5.0_darwin_arm64 plugin: 2024/02/08 13:21:31 [DEBUG] Error getting SSH address: open /Library/Preferences/Parallels/parallels_dhcp_leases: no such file or directory

### PR DESCRIPTION
**Pull request by bineesh-n**
Splitted IPAddress function into two. The first one will find ip with leases file. Second one will find ip with prlctl, if first attempt failed. 

Closes #103

### CODE REVIEW

File: builder/parallels/common/driver_9.go [hunk 1]
```diff
@@ -493,34 +490,46 @@ func (d *Parallels9Driver) IPAddress(mac string, vmName string) (string, error)
...
+	return mostRecentIP, nil
+}
 
-		stdoutString := strings.TrimSpace(stdout.String())
-		re := regexp.MustCompile(`([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)`)
-		macMatch := re.FindAllStringSubmatch(stdoutString, 1)
+func (d *Parallels9Driver) ipWithPrlctl(vmName string) (string, error) {
+	ip := ""
+	var stdout bytes.Buffer
+	cmd := exec.Command(d.PrlctlPath, "list", vmName, "--full", "--no-header", "-o", "ip_configured")
```
Comment (cjlapao) [inline builder/parallels/common/driver_9.go:499]: I would also add a stderr and check if there is something there, prlctl has a hit and miss when it comes to have an error but the exit code is still 0.

I know we have a regex check later on, so if the output is empty it will be catch there so it is up to you

**Review by cjlapao — APPROVED** [review]

File: builder/parallels/common/driver_9.go (hunk 1 above)
Comment (bineesh-n) [reply builder/parallels/common/driver_9.go:499]: You are right. For a safer side, I've added & printed stderr now.

**Review by cjlapao — APPROVED** [review]
